
eureka:
  client:
    register-with-eureka: true
  instance:
    metadata-map:
      crewmodule: "crewmodule"
      module-name: "BidPoints"
      service-path: "/path/to/menuItem"
      owning-team: "Nimbus"

spring:
  # Enabling h2 console, accessible at http://localhost:8080/h2-console (use JDBC URL: jdbc:h2:mem:testdb, user: sa, password: empty (leave blank))
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false

logging:
  level:
    ROOT: INFO
    org.hibernate.stat: INFO
    org.hibernate.type: INFO
