server:
  port: 20202

eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  routes:
    items-webapi:
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      stripPrefix: false

management:
  endpoints:
    web:
      exposure:
        include: "*"