server:
  port: 8100

eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true

swagger:
  api-version: 1.0
  enabled: true
  title: "Items and reviews web API"
  description: "Sample Swagger implementation for the `webapi` service, leveraging annotations at the controller-method level."
  useDefaultResponseMessages: false
  enableUrlTemplating: false
  deepLinking: true
  defaultModelsExpandDepth: 1
  defaultModelExpandDepth: 1
  displayOperationId: false
  displayRequestDuration: false
  filter: false
  maxDisplayedTags: 0
  showExtensions: false